#!/usr/bin/env python3
"""Generates data/tools.json from the hardcoded transcription of the source
comparison doc (project_pantheon/docs/feature-comparison.md, section 6 cross
table + section 5 thinner entries). No web calls, no invented data."""
import json
import os

MARKS = {"yes", "partial", "experimental", "planned", "no", "undocumented", "unknown", "n/a", "info"}

# Groups render as full-width heading rows in the matrix view, in this fixed order.
G_AGENTS = "Agents & supervision"
G_SESSIONS = "Sessions & views"
G_USAGE = "Usage & limits"
G_TASKS = "Tasks, planning & merging"
G_REMOTE = "Remote & mobile"
G_HOOD = "Under the hood"
G_PROJECT = "Project & openness"
GROUP_ORDER = [G_AGENTS, G_SESSIONS, G_USAGE, G_TASKS, G_REMOTE, G_HOOD, G_PROJECT]

FEATURES = [
    ("multi_provider_supervision", "Runs more than one kind of agent", "Can drive more than one coding agent (Claude Code, Codex and so on) side by side.", G_AGENTS),
    ("harness_count", "Coding agents supported", "How many different coding agents it can run, per its own docs.", G_AGENTS),
    ("needs_you_signal", "Alerts when you're needed", "How it tells you an agent is waiting on you.", G_AGENTS),
    ("approve_deny_prompt", "Answer \"Allow?\" prompts from the manager", "When an agent stops to ask permission (run this command? edit this file?), you can allow or deny it from the manager or your phone instead of opening that agent's own window.", G_AGENTS),
    ("cross_provider_delegation", "Hand-offs between agents in one view", "Work passed from one agent to another shows up in the same place.", G_AGENTS),
    ("always_on_assistant", "Always-on assistant", "A standing assistant session you can reach any time.", G_AGENTS),
    ("conversation_gui_view", "Chat view of a session", "Read a session as a conversation instead of raw terminal text.", G_SESSIONS),
    ("real_terminal", "Open the real terminal", "Drop into the session's actual terminal.", G_SESSIONS),
    ("session_organization", "How sessions are organized", "List, worktrees, kanban or nested groups.", G_SESSIONS),
    ("prompt_scratchpad", "Prompt drafts", "Draft prompts and insert them without sending.", G_SESSIONS),
    ("saved_prompt_library", "Saved prompts", "Reusable prompts you can fire with context attached.", G_SESSIONS),
    ("builtin_editors_browser", "Built-in editor / browser", "Ships its own editor or browser.", G_SESSIONS),
    ("appearance_control", "Look and font control", "How far you can change its look, including your terminal's font.", G_SESSIONS),
    ("usage_hud", "Shows your usage limits", "Your subscription usage and resets, read from local logs.", G_USAGE),
    ("burn_rate_forecast", "Predicts when you'll hit a limit", "Burn rate and time to the limit, not just current usage.", G_USAGE),
    ("limit_governor", "Pause and resume at usage limits", "Pauses work near a limit and picks it back up after the reset.", G_USAGE),
    ("account_hotswap", "Switch accounts without logging in again", "Move between provider accounts without re-login.", G_USAGE),
    ("vault_task_source", "Tasks from your notes vault", "Reads your own notes vault (such as Obsidian) as the task list.", G_TASKS),
    ("issue_tracker_pipeline", "Turns GitHub or Jira issues into pull requests", "Picks up an issue from GitHub, GitLab, Linear or Jira, hands it to an agent, and carries the resulting pull request through review.", G_TASKS),
    ("worktree_management", "Manages git worktrees", "Gives each agent or task its own git worktree.", G_TASKS),
    ("planner_orchestrator", "Planner that splits the work", "Breaks a goal into parts and runs them.", G_TASKS),
    ("agent_to_agent_messaging", "Agents message each other", "One session can message or query another.", G_TASKS),
    ("knowledge_base", "Knowledge base for agents", "A notes store agents can look things up in.", G_TASKS),
    ("native_mobile_app", "Phone app", "A dedicated iOS or Android app.", G_REMOTE),
    ("phone_no_new_app", "Phone access with no new app", "Reach it from your phone with tools you already have.", G_REMOTE),
    ("remote_ssh", "Remote machines over SSH", "Run or edit sessions on another machine.", G_REMOTE),
    ("voice_input", "Voice input", "Dictate to it.", G_REMOTE),
    ("os", "Operating systems", "Which systems it runs on, plus phone or browser access, per its own release files or docs.", G_HOOD),
    ("app_shell", "App shell", "What the app is built on: Electron, Tauri, a terminal UI, or a hosted service.", G_HOOD),
    ("languages", "Main languages", "Top languages in its repo, from GitHub's breakdown.", G_HOOD),
    ("background_process", "Background process", "Whether it runs a separate server or daemon next to the app.", G_HOOD),
    ("download_size", "Download size", "Installer size from its latest release. Not memory use.", G_HOOD),
    ("ram_vs_claude_desktop", "Memory vs Claude Desktop", "Size as a share of Claude Desktop, which measured about 7.5 GB on one Windows PC on 2026-09-28 (about 3.7 GB for the app across 24 processes, plus about 4 GB for the virtual machine it starts for Cowork). Scale: Tiny = under 5%, Small = 5-15%, Medium = 15-40%. Measured where the cell says so; otherwise an estimate from what the tool is built on. The coding agents themselves cost the same under every tool.", G_HOOD),
    ("runs_in_terminal", "Runs in your own terminal", "Lives inside the terminal you already use.", G_HOOD),
    ("license_cost", "License / cost", "Open-source license or pricing.", G_PROJECT),
    ("extensibility", "Plugins / SDK", "Outside developers can extend it.", G_PROJECT),
    ("teams_multiuser", "Teams", "Built for more than one person.", G_PROJECT),
    ("stability_maturity", "Maturity", "How far along and how stable it is.", G_PROJECT),
]

def c(mark, value):
    assert mark in MARKS, mark
    return {"value": value, "mark": mark}

# ---- Orca ----
orca = {
    "name": "Orca", "url": "https://onorca.dev", "category": "agent manager",
    "where_agents_run": "your machine + remote (SSH worktrees, headless Linux server, phone companion)",
    "license": "MIT, free", "checked_on": "2026-09-22 (installed + shipped-code read)",
    "source_note": "Source-verified: installed desktop + phone, shipped app.asar read, own docs.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "27+ agents / \"any CLI agent\""),
        "harness_count": c("info", "27+ (\"any CLI agent\")"),
        "needs_you_signal": c("yes", "Hook-driven + unread/attention state"),
        "approve_deny_prompt": c("unknown", "Not verified"),
        "conversation_gui_view": c("experimental", "Experimental Chat UI"),
        "real_terminal": c("yes", "Embedded GPU terminal, infinite splits, restored scrollback"),
        "session_organization": c("yes", "Worktree per task"),
        "usage_hud": c("yes", "Local state + account read, 6 providers, weekly resets, 80% warning chip"),
        "burn_rate_forecast": c("no", "Usage % and reset windows only, no burn rate or forecast"),
        "limit_governor": c("no", "None"),
        "vault_task_source": c("no", "Task providers are GitHub, GitLab, Linear, Jira only"),
        "issue_tracker_pipeline": c("yes", "GitHub, GitLab, Linear, Jira"),
        "worktree_management": c("yes", "Core: every task gets one, fan-out across N, SSH worktrees"),
        "planner_orchestrator": c("experimental", "Experimental Orchestration (CLI-driven), off by default"),
        "agent_to_agent_messaging": c("experimental", "Via experimental Orchestration"),
        "cross_provider_delegation": c("yes", "Visible in one place"),
        "always_on_assistant": c("no", "None"),
        "knowledge_base": c("no", "None"),
        "builtin_editors_browser": c("yes", "Browser and computer-use via its CLI"),
        "native_mobile_app": c("experimental", "Companion app, beta"),
        "phone_no_new_app": c("no", "Requires its own companion app"),
        "remote_ssh": c("yes", "SSH worktrees + Remote Server (beta)"),
        "account_hotswap": c("yes", "Hot-swap between Codex accounts without re-login"),
        "prompt_scratchpad": c("unknown", "Not verified"),
        "saved_prompt_library": c("unknown", "Not verified"),
        "appearance_control": c("yes", "Terminal font, theme, cursor and padding; imports Ghostty and Warp themes (docs, 2026-09-29)"),
        "extensibility": c("partial", "Scriptable CLI and installable agent skills; no plugin system or SDK (docs, 2026-09-29)"),
        "teams_multiuser": c("unknown", "Not verified"),
        "voice_input": c("unknown", "Not verified"),
        "license_cost": c("info", "MIT, free, uses your own subscriptions"),
        "app_shell": c("info", "Electron 43.7.5"),
        "languages": c("info", "TypeScript ~95%, JavaScript ~4%, Swift <1%"),
        "background_process": c("info", "Yes: a daemon-host process (docs/reference/windows-daemon-host-relocation.md)"),
        "download_size": c("info", "v1.4.216: 193 MB Windows setup.exe, 218-226 MB mac dmg, 207-209 MB Linux AppImage"),
        "ram_vs_claude_desktop": c("info", "Medium: about 30% (measured 2.3 GB with five projects and agents running)"),
        "runs_in_terminal": c("no", "Embeds its own GPU terminal instead"),
        "stability_maturity": c("info", "\"Features shipped daily\"; chat, orchestration and mobile are experimental"),
    },
}

# ---- VelaTerm ----
velaterm = {
    "name": "VelaTerm", "url": "https://velaterm.com", "category": "agent manager",
    "where_agents_run": "your machine + remote (SSH), plus browser pairing and a phone app",
    "license": "MIT, v0.2.x, free", "checked_on": "2026-09-28, author's posts only",
    "source_note": "Not independently verified — every cell comes from two of the developer's own launch posts, not the repo or site.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "8+ named agents (Claude Code, Codex, OpenCode, Copilot, Cursor, Antigravity, Cline, Pi) \"and more\""),
        "harness_count": c("info", "8+ (Claude Code, Codex, OpenCode, Copilot, Cursor, Antigravity, Cline, Pi...)"),
        "needs_you_signal": c("yes", "Live status plus phone push (underlying mechanism not stated)"),
        "approve_deny_prompt": c("yes", "\"Answer agents\" from the phone"),
        "conversation_gui_view": c("yes", "Default view, plus the same session's terminal view alongside it"),
        "real_terminal": c("yes", "Each session is a real PTY that keeps running in the background"),
        "session_organization": c("yes", "Projects, then nested groups to any depth, then sessions"),
        "usage_hud": c("yes", "Plan quota, context and tokens in its side panel (README, checked 2026-09-29)"),
        "burn_rate_forecast": c("undocumented", "Not mentioned in its launch posts"),
        "limit_governor": c("undocumented", "Not mentioned in its launch posts"),
        "vault_task_source": c("no", "Has a notes knowledge base, not a task queue"),
        "issue_tracker_pipeline": c("unknown", "Not claimed either way"),
        "worktree_management": c("yes", "Optional per launch: none, one shared worktree, or one per session"),
        "planner_orchestrator": c("yes", "Plan/Execute: a planner splits the task, you approve the split, executors build each part in parallel"),
        "agent_to_agent_messaging": c("yes", "Search another session's conversation, ask about it, or message/steer a running session, across providers"),
        "cross_provider_delegation": c("yes", "Visible in one place"),
        "always_on_assistant": c("no", "None"),
        "knowledge_base": c("yes", "Save what a session learned; agents query it before acting; local code-graph queries with no model call"),
        "builtin_editors_browser": c("yes", "Markdown editor, code editor, image viewer, browser tab, also usable remotely"),
        "native_mobile_app": c("yes", "iOS/Android app with push notifications"),
        "phone_no_new_app": c("yes", "Any browser via an end-to-end-encrypted pairing link, no install"),
        "remote_ssh": c("yes", "SSH including editing remote files"),
        "account_hotswap": c("unknown", "Not claimed either way"),
        "prompt_scratchpad": c("unknown", "Not claimed either way"),
        "saved_prompt_library": c("unknown", "Not claimed either way"),
        "appearance_control": c("unknown", "Not claimed either way"),
        "extensibility": c("unknown", "Not claimed either way"),
        "teams_multiuser": c("partial", "Account device list"),
        "voice_input": c("unknown", "Not claimed either way"),
        "license_cost": c("info", "MIT, free, uses your own subscriptions"),
        "app_shell": c("info", "Tauri 2 (Rust + system WebView); repo also carries a secondary Electron shell, not the primary build"),
        "languages": c("info", "TypeScript ~46%, Rust ~39%, Python ~8%"),
        "background_process": c("unknown", "not verified: a minimal headless `vela-server` build exists but isn't documented as running alongside the desktop app"),
        "download_size": c("info", "v0.2.5: 59 MB Windows min-setup / 148 MB full-setup, 49-51 MB mac dmg"),
        "ram_vs_claude_desktop": c("info", "Small (estimate: Tauri app on the system WebView)"),
        "runs_in_terminal": c("no", "Own app; the Windows installer bundles Git Bash"),
        "stability_maturity": c("info", "v0.2.x, launched 2026-09-28, not independently verified"),
    },
}

# ---- Pantheon ----
herdr = {
    "name": "herdr", "url": "https://herdr.dev", "category": "agent manager",
    "where_agents_run": "your machine + saved SSH machines, in one window",
    "license": "Apache-2.0, free", "checked_on": "2026-09-28 (repo README, release assets, herdr.dev and its integrations docs)",
    "source_note": "Checked against its own README, latest release (v0.9.1), herdr.dev and the integrations docs. Not installed or run here.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Claude Code, Codex, Cursor, opencode, Grok and more; it owns their terminals rather than wrapping them"),
        "harness_count": c("info", "22 detected out of the box"),
        "needs_you_signal": c("partial", "Every pane marked working, blocked or idle, read from the screen (hooks are used only to restore sessions)"),
        "approve_deny_prompt": c("no", "Marks the pane blocked; you answer in the pane itself"),
        "conversation_gui_view": c("no", "Terminal panes only"),
        "real_terminal": c("yes", "Every agent runs in its own real pane"),
        "session_organization": c("yes", "Workspaces and split panes, with one agent list across local and SSH machines"),
        "prompt_scratchpad": c("undocumented", "Not mentioned in its docs"),
        "saved_prompt_library": c("undocumented", "Not mentioned in its docs"),
        "builtin_editors_browser": c("no", "Runs your tools in panes; no editor or browser of its own"),
        "appearance_control": c("partial", "Uses the terminal you already have; its own configuration file"),
        "usage_hud": c("no", "None in its docs or changelog (checked 2026-09-29); the rate-limit line in its demo is Claude Code's own status line"),
        "burn_rate_forecast": c("undocumented", "Not mentioned in its docs"),
        "limit_governor": c("undocumented", "Not mentioned in its docs"),
        "account_hotswap": c("undocumented", "Not mentioned in its docs"),
        "vault_task_source": c("no", "No task source"),
        "issue_tracker_pipeline": c("no", "None in its docs, changelog or code (checked 2026-09-29)"),
        "worktree_management": c("yes", "Creates, opens and removes worktrees from the sidebar or the herdr worktree command (changelog, checked 2026-09-29)"),
        "planner_orchestrator": c("partial", "No planner of its own, but agents can spawn panes and prompt each other through its CLI and socket API"),
        "agent_to_agent_messaging": c("yes", "Agents spawn panes, prompt each other and wait until another agent is really blocked (socket API + agent skill)"),
        "cross_provider_delegation": c("yes", "All agents in one list, local and remote"),
        "always_on_assistant": c("no", "None"),
        "knowledge_base": c("no", "None"),
        "native_mobile_app": c("no", "None (a separate community macOS console, herdrm, exists)"),
        "phone_no_new_app": c("yes", "Any SSH app reattaches to the background server"),
        "remote_ssh": c("yes", "Saved SSH machines sit beside local ones with independent reconnects; a hosted option is announced"),
        "voice_input": c("undocumented", "Not mentioned in its docs"),
        "app_shell": c("info", "Terminal UI: one Rust binary, no Electron"),
        "languages": c("info", "Rust ~93%, Python ~3%"),
        "background_process": c("info", "Yes: a background server keeps terminals running after you close the client or lose SSH"),
        "download_size": c("info", "v0.9.1: 9 MB Windows zip, 20-22 MB macOS, 23-25 MB Linux"),
        "ram_vs_claude_desktop": c("info", "Tiny (estimate: terminal app, one small Rust binary)"),
        "runs_in_terminal": c("yes", "Runs in whatever terminal you already use"),
        "license_cost": c("info", "Apache-2.0, free, uses your own subscriptions"),
        "extensibility": c("yes", "Plugin marketplace plus a CLI and socket API"),
        "teams_multiuser": c("undocumented", "Not mentioned in its docs"),
        "stability_maturity": c("info", "v0.9.1, ~41k GitHub stars, fast-moving; Windows build is in beta"),
    },
}

pantheon = {
    "name": "Pantheon", "url": "https://github.com/dtiger1889-ops/pantheon", "category": "agent manager",
    "where_agents_run": "your machine (terminal-native, tmux-hosted; phone reaches it over an existing SSH tunnel)",
    "license": "MIT, free, your own subscriptions", "checked_on": "2026-09-28 (author's own build, cells refreshed for the 2026-09-22..27 builds)",
    "source_note": "Author's own project (open source, pre-release, published as-is). Held to the same rules as every other tool here, weak spots included.",
    "is_authors_own": True,
    "features": {
        "multi_provider_supervision": c("yes", "Hooks-based"),
        "harness_count": c("info", "2 (Claude Code, Codex); local models planned"),
        "needs_you_signal": c("yes", "Exact: derived from hook events, not inferred from silence"),
        "approve_deny_prompt": c("partial", "Allow/deny/view a waiting prompt from the deck, built, not yet tested live"),
        "conversation_gui_view": c("partial", "Detail panel shows recent actions and the latest ask read from the transcript, not a full chat view"),
        "real_terminal": c("yes", "Clicking a session opens its own real tmux window"),
        "session_organization": c("yes", "Sidebar session list plus a live fleet table"),
        "usage_hud": c("yes", "Shipped, from local logs; reading the same account-usage numbers claude.ai shows is built, not yet tested live"),
        "burn_rate_forecast": c("partial", "Built, with ranges; not yet checked against real usage"),
        "limit_governor": c("partial", "Built: wind down near a limit, park, and resume after reset, plus limit hand-off to another provider and timed starts; not yet tested live, off by default"),
        "vault_task_source": c("yes", "Unique in this table: reads a personal notes vault directly as its live task source"),
        "issue_tracker_pipeline": c("no", "Deliberately absent; the notes vault is the tracker"),
        "worktree_management": c("no", "Agents use worktrees; the deck itself doesn't manage them"),
        "planner_orchestrator": c("planned", "Planning card built; dispatching from it is still greyed out"),
        "agent_to_agent_messaging": c("no", "None"),
        "cross_provider_delegation": c("yes", "Visible in the deck, with auto-fallback to console mode"),
        "always_on_assistant": c("partial", "Pinned Assistant window built; reachable from the phone over the existing remote-control link"),
        "knowledge_base": c("n/a", "Reads the vault only as a task list"),
        "builtin_editors_browser": c("partial", "A terminal editor pane is built"),
        "native_mobile_app": c("no", "Reuses a terminal app over an existing SSH tunnel at a narrower column width instead"),
        "phone_no_new_app": c("yes", "Reuses an existing terminal app and SSH tunnel already on the phone"),
        "remote_ssh": c("no", "None"),
        "account_hotswap": c("no", "None"),
        "prompt_scratchpad": c("yes", "Autosaved tabbed drafts, insert-without-send, slash completion"),
        "saved_prompt_library": c("planned", "Idea logged, not built"),
        "appearance_control": c("yes", "Unusual for this table: palette and per-token overrides write directly into the host terminal's own settings file"),
        "extensibility": c("no", "None"),
        "teams_multiuser": c("no", "Single-user by design"),
        "voice_input": c("no", "None"),
        "license_cost": c("info", "MIT, free; pre-release, published as-is; uses your own subscriptions"),
        "app_shell": c("info", "Terminal UI: Python 3.12 + Textual, running inside your existing terminal, no separate installer"),
        "languages": c("info", "Python (Textual TUI)"),
        "background_process": c("info", "Yes: a separate small Python usage-collector process alongside the Textual UI process"),
        "download_size": c("info", "No installer; runs from source (git clone + Python)"),
        "ram_vs_claude_desktop": c("info", "Tiny: about 1% (measured 77 MB)"),
        "runs_in_terminal": c("yes", "Runs inside the terminal you already have, under tmux"),
        "stability_maturity": c("info", "Personal, pre-release; its terminal-multiplexer server froze four times on one day (cause still open)"),
    },
}

# ---- Paseo ----
paseo = {
    "name": "Paseo", "url": "https://paseo.sh", "category": "agent manager",
    "where_agents_run": "your machine + cloud (self-hosted relay or Tailscale) + mobile + web",
    "license": "Apache-2.0, free", "checked_on": "2026-09-06 (source- and hands-on-verified)",
    "source_note": "Source-verified and installed/live-tested.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Deep per-provider SDK adapters"),
        "harness_count": c("info", "~39"),
        "needs_you_signal": c("yes", "SDK-level"),
        "approve_deny_prompt": c("yes", "Dedicated control-plane tool to respond to a permission request"),
        "conversation_gui_view": c("yes", "Shows messages, reasoning and tool calls as a readable timeline (changelog and docs, 2026-09-29)"),
        "real_terminal": c("yes", "Yes"),
        "session_organization": c("yes", "Per workspace"),
        "usage_hud": c("partial", "Risky reverse-engineered endpoint, display-only, no rate-limit mitigation seen"),
        "burn_rate_forecast": c("no", "None"),
        "limit_governor": c("no", "None"),
        "vault_task_source": c("no", "None"),
        "issue_tracker_pipeline": c("partial", "Mention its bot on a GitHub issue and an agent works it and can open a PR; GitHub only, no Jira, Linear or GitLab (Paseo Hub, 2026-09-29)"),
        "worktree_management": c("yes", "Mature: rollback, recovery, git-contention queue"),
        "planner_orchestrator": c("yes", "The agent itself gets control-plane tools such as creating agents and responding to permission requests"),
        "agent_to_agent_messaging": c("yes", "Via its control-plane tools"),
        "cross_provider_delegation": c("yes", "Visible in one place"),
        "always_on_assistant": c("no", "None"),
        "knowledge_base": c("no", "None"),
        "builtin_editors_browser": c("unknown", "Not stated in this doc"),
        "native_mobile_app": c("yes", "Native iOS and Android apps"),
        "phone_no_new_app": c("no", "Requires its own app"),
        "remote_ssh": c("yes", "Via its daemon"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-06)"),
        "prompt_scratchpad": c("no", "None"),
        "saved_prompt_library": c("no", "None"),
        "appearance_control": c("yes", "App theme, interface and code fonts, text sizes, content width (GitHub, 2026-09-29)"),
        "extensibility": c("yes", "MCP server, CLI and TypeScript SDK for automation"),
        "teams_multiuser": c("yes", "Teams plus triggers from GitHub/Slack/Discord"),
        "voice_input": c("yes", "Yes"),
        "license_cost": c("info", "Apache-2.0, free"),
        "app_shell": c("info", "Electron 44.2.0"),
        "languages": c("info", "TypeScript ~98%, JavaScript ~1%"),
        "background_process": c("info", "Yes: a Node daemon (package.json `dev:server` runs `PASEO_LISTEN=... dev-daemon.sh`)"),
        "download_size": c("info", "v0.10.0: 137 MB Windows Setup x64, 186 MB mac x64 dmg, 129 MB Linux .deb"),
        "ram_vs_claude_desktop": c("info", "Medium (estimate: Electron app plus a background server)"),
        "runs_in_terminal": c("no", "Own desktop/mobile/web app"),
        "stability_maturity": c("info", "Mature"),
    },
}

# ---- Kepler ----
kepler = {
    "name": "GitKraken Kepler", "url": "https://www.gitkraken.com/kepler", "category": "agent manager",
    "where_agents_run": "your machine (Win/Mac/Linux) plus SSH/WSL remote execution",
    "license": "commercial, free tier", "checked_on": "2026-09-06 (site-verified)",
    "source_note": "Site-verified, not installed.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Agent-agnostic model choice per task"),
        "harness_count": c("info", "\"Any agent\" (not counted)"),
        "needs_you_signal": c("yes", "Yes"),
        "approve_deny_prompt": c("unknown", "Not stated"),
        "conversation_gui_view": c("yes", "Agent Graph: live tree of every session, turn, tool call and subagent"),
        "real_terminal": c("unknown", "Not stated"),
        "session_organization": c("yes", "Three views of one fleet: live, kanban, dense list"),
        "usage_hud": c("no", "Org-level spend analytics, not a live burn view"),
        "burn_rate_forecast": c("no", "None"),
        "limit_governor": c("no", "None"),
        "vault_task_source": c("no", "None"),
        "issue_tracker_pipeline": c("yes", "Jira, Trello, GitHub, GitLab Issues, Linear"),
        "worktree_management": c("yes", "Parallel worktrees with per-branch diffs, plus setup hooks that run repo scripts before the agent starts"),
        "planner_orchestrator": c("undocumented", "Not in its feature list (checked 2026-09-06)"),
        "agent_to_agent_messaging": c("no", "None"),
        "cross_provider_delegation": c("yes", "Visible in one place"),
        "always_on_assistant": c("no", "None"),
        "knowledge_base": c("no", "None"),
        "builtin_editors_browser": c("yes", "Diffs plus in-app commit/PR"),
        "native_mobile_app": c("partial", "Mobile check-and-answer, not a full session manager"),
        "phone_no_new_app": c("no", "Requires its own app"),
        "remote_ssh": c("yes", "SSH/WSL remote execution"),
        "account_hotswap": c("undocumented", "Not in its feature list (checked 2026-09-06)"),
        "prompt_scratchpad": c("partial", "\"Actions\": saved one-click prompts"),
        "saved_prompt_library": c("yes", "Actions come with issue, diff and repo state pre-attached"),
        "appearance_control": c("yes", "Two themes, dark/light/system, terminal font and spacing (help docs, 2026-09-29)"),
        "extensibility": c("partial", "Custom Actions: your own prompt, agent and skill per action; no plugins, SDK or API (help docs, 2026-09-29)"),
        "teams_multiuser": c("yes", "Org-level analytics on agent spend"),
        "voice_input": c("no", "None"),
        "license_cost": c("info", "Commercial with a free tier"),
        "app_shell": c("unknown", "not verified: not stated on gitkraken.com/kepler or help.gitkraken.com; not extrapolated from GitKraken's separate main git client"),
        "languages": c("unknown", "not verified: closed source, no public repo"),
        "background_process": c("unknown", "not verified"),
        "download_size": c("unknown", "not verified: not stated on the vendor's pages"),
        "ram_vs_claude_desktop": c("unknown", "not verified: app shell unknown"),
        "runs_in_terminal": c("no", "Own desktop app"),
        "stability_maturity": c("info", "Commercial product"),
    },
}

# ---- AO ----
ao = {
    "name": "Agent Orchestrator (AO)", "url": "https://github.com/Untrivial-ai/agent-orchestrator", "category": "agent manager",
    "where_agents_run": "your machine + mobile companion (LAN/Tailscale)",
    "license": "Apache-2.0, free, ~12.5k stars", "checked_on": "2026-09-06 (site-verified)",
    "source_note": "Site-verified, not installed.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "25 harnesses, per-project defaults"),
        "harness_count": c("info", "25+"),
        "needs_you_signal": c("yes", "Escalates only what needs a human"),
        "approve_deny_prompt": c("yes", "Escalations to a human"),
        "conversation_gui_view": c("yes", "Yes"),
        "real_terminal": c("unknown", "Not stated"),
        "session_organization": c("yes", "Kanban board: Pending / Iterating / In Review / Ready-to-merge"),
        "usage_hud": c("no", "None"),
        "burn_rate_forecast": c("no", "None"),
        "limit_governor": c("no", "None"),
        "vault_task_source": c("no", "None"),
        "issue_tracker_pipeline": c("yes", "CI feedback loop: failed checks and review comments route back to the owning session until approved"),
        "worktree_management": c("yes", "Orchestrator spawns worktree workers per task"),
        "planner_orchestrator": c("yes", "Core: a per-project main orchestrator agent that plans and spawns worktree workers; orchestrators can message each other"),
        "agent_to_agent_messaging": c("yes", "Orchestrators message other orchestrators"),
        "cross_provider_delegation": c("yes", "Visible in one place"),
        "always_on_assistant": c("no", "None"),
        "knowledge_base": c("no", "None"),
        "builtin_editors_browser": c("unknown", "Not stated"),
        "native_mobile_app": c("yes", "Mobile companion with working/need-you/mergeable counts"),
        "phone_no_new_app": c("no", "Requires its own companion app"),
        "remote_ssh": c("unknown", "Not stated"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-06)"),
        "prompt_scratchpad": c("no", "None"),
        "saved_prompt_library": c("no", "None"),
        "appearance_control": c("partial", "Light/dark and named color themes; no font setting found (source, 2026-09-29)"),
        "extensibility": c("partial", "Scriptable ao CLI over a local API; its plugin system was removed in the Go rewrite (docs, 2026-09-29)"),
        "teams_multiuser": c("planned", "Organizations and sharing are built for AO Cloud, which is waitlist-only (site and repo, 2026-09-29)"),
        "voice_input": c("no", "None"),
        "license_cost": c("info", "Apache-2.0, free (license per GitHub, 2026-09-29)"),
        "app_shell": c("info", "Electron ^33.0.0 (frontend/package.json), plus a separate Go backend"),
        "languages": c("info", "Go ~59%, TypeScript ~38%"),
        "background_process": c("info", "Yes: a separate Go backend process (repo has a distinct backend/ Go module via go.work, apart from the Electron frontend/)"),
        "download_size": c("info", "v0.13.2-nightly: 136 MB Windows Setup.exe, 177-189 MB mac zip, 181 MB Linux AppImage"),
        "ram_vs_claude_desktop": c("info", "Medium (estimate: Electron app plus a Go backend)"),
        "runs_in_terminal": c("no", "Own desktop app"),
        "stability_maturity": c("info", "Active development"),
    },
}

# ---- Thinner §5 entries: unknown for every §6-style feature, only what §5 explicitly states filled in ----
def thin(name, url, category, where, license_, note, extra=None):
    t = {
        "name": name, "url": url, "category": category, "where_agents_run": where,
        "license": license_, "checked_on": "2026-09-07 (site/discussion pass only, no full comparison run)",
        "source_note": note, "is_authors_own": False,
        "features": {k: c("unknown", "not verified") for k, _, _, _ in FEATURES},
    }
    if extra:
        for k, v in extra.items():
            t["features"][k] = v
    return t

ccmanager = thin(
    "CCManager", "https://github.com/kbwo/ccmanager", "agent manager", "your machine (Linux/macOS)",
    "unknown", "Evaluated and not adopted (2026-09-01). Terminal session manager; state detection parses tool output rather than reading structured hook events.",
    {"needs_you_signal": c("partial", "Output-parsed, coarser than hook-event-based detection"),
     "runs_in_terminal": c("yes", "TUI session manager")},
)

opencove = thin(
    "OpenCove", "https://github.com/DeadWaveWave/opencove", "agent manager", "your machine (desktop)",
    "unknown", "Alpha desktop canvas of agent sessions, used here as a visual-design reference; its state-detection mechanism is undocumented.",
)

superset = thin(
    "Superset", "https://superset.sh", "agent manager", "your machine (macOS, experimental Linux)",
    "Elastic-2.0", "Site/discussion pass only, 2026-09-07. Ships a TypeScript SDK and MCP server so agents can spawn agents.",
    {"extensibility": c("yes", "TypeScript SDK plus MCP server so agents can spawn agents"),
     "license_cost": c("info", "Elastic-2.0")},
)

conductor = thin(
    "Conductor", "https://www.conductor.build", "agent manager", "your machine (macOS only)",
    "proprietary", "Site/discussion pass only, 2026-09-07. Checkpoint/rollback called best-in-class.",
    {"license_cost": c("info", "Proprietary")},
)

jenny = thin(
    "Jenny", "https://github.com/SaltyPretz3l/jenny", "other tool we looked at", "your machine",
    "MIT", "A single-agent local-LLM chat app and IDE (llama.cpp / vLLM / any OpenAI-compatible endpoint), not a fleet manager, so it doesn't compete on most rows here. Recorded for its file-edit checkpointing, destructive-command approval, and a scratchpad/calendar the model can read and modify.",
    {"multi_provider_supervision": c("no", "Single local-model chat app, not a multi-agent fleet manager"),
     "license_cost": c("info", "MIT")},
)

micracode = thin(
    "micracode", "https://github.com/Jamessdevops/micracode", "other tool we looked at", "your machine",
    "open-source", "An AI web-app builder (Next.js, exports components as a zip), a different category from a fleet manager; recorded for completeness only. Local-model support is planned by its author.",
    {"multi_provider_supervision": c("no", "App builder, not a fleet/agent manager"),
     "license_cost": c("info", "open-source")},
)

teleclod = thin(
    "Teleclod", "https://teleclod.com", "agent manager", "cloud (Windows/macOS/Linux/Android/browser plus a Chrome extension)",
    "commercial (Free / EUR49 Pro / EUR99 Studio)", "Site-only pass, 2026-09-22; no independent verification found (no reviews, repo, or discussion beyond the single source comment).",
    {"multi_provider_supervision": c("yes", "Claims 14+ providers including Claude Code, Codex, OpenRouter, Ollama, Kimi"),
     "usage_hud": c("undocumented", "Not mentioned on its site"),
     "vault_task_source": c("no", "It is its own task store"),
     "limit_governor": c("no", "None"),
     "session_organization": c("yes", "Task list, kanban, and a global dashboard"),
     "runs_in_terminal": c("no", "Replaces the terminal outright"),
     "license_cost": c("info", "Closed-source, paid tiers")},
)

oyren = thin(
    "Oyren", "https://oyren.ai/development", "agent manager", "cloud (remote codespaces, deliberately not your machine)",
    "commercial, hourly", "Site-verified, 2026-09-23. Remote disposable codespaces with several agent CLIs preinstalled and tmux in every codespace.",
    {"multi_provider_supervision": c("yes", "Claude Code, Codex, Cursor, opencode, Qwen Code, DeepSeek Harness, Antigravity preinstalled"),
     "usage_hud": c("undocumented", "Not mentioned on its site"),
     "vault_task_source": c("no", "Its own kanban board is the tracker"),
     "limit_governor": c("partial", "A blocked card emails the human a specific question and resumes on reply, but only for one card, not a whole session against a usage window"),
     "issue_tracker_pipeline": c("yes", "Its own kanban board with an importance/urgency matrix and calendar/milestone views, read and written by agents over its own MCP server"),
     "builtin_editors_browser": c("yes", "Streamed VS Code/Zed IDE plus a Playwright-driven built-in browser"),
     "remote_ssh": c("n/a", "Hosted service: it already is the remote machine"),
     "app_shell": c("info", "Hosted cloud service, browser-based, no local install (vendor: \"VS Code runs as web app in your browser while Zed editor is streamed\")"),
     "background_process": c("n/a", "Hosted service: nothing runs on your machine"),
     "ram_vs_claude_desktop": c("info", "Runs in the cloud (local cost: a browser tab)"),
     "runs_in_terminal": c("no", "Cloud codespace, not a local terminal tool"),
     "license_cost": c("info", "Commercial: hourly compute plus an optional credit wallet")},
)

# ---- Added 2026-09-29 with a research pass each; sources in project_pantheon/archive/research_raw/2026-09-29-new-agent-managers/ ----
# Research entry for Google Antigravity 2.0 (https://antigravity.google), checked 2026-09-29.
# Shape matches the orca/ao entries in portfolio_repos/agent-deck-comparison/tools/build_data.py.
# Findings and sources: project_pantheon/archive/research_raw/2026-09-29-new-agent-managers/antigravity.md
antigravity = {
    "name": "Google Antigravity", "url": "https://antigravity.google", "category": "agent manager",
    "where_agents_run": "your machine (projects, local folders or git worktrees, optional WSL connection on Windows), driven from any browser or phone through its Remote Control web page",
    "license": "Proprietary, closed source; free tier plus paid Google AI plans", "checked_on": "2026-09-29 (docs/site pass)",
    "source_note": "Docs-verified: official docs, changelog, launch blog and download page read; installer sizes and app shell read from the v2.18.1 downloads; not installed or run.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Gemini, Claude or GPT, switched per task"),
        "harness_count": c("info", "3: Gemini, Claude, GPT"),
        "needs_you_signal": c("yes", "Desktop notification and chime; phone push"),
        "approve_deny_prompt": c("yes", "Approval card in the app or on your phone"),
        "cross_provider_delegation": c("partial", "Subagents show as cards; only its own agents"),
        "always_on_assistant": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "conversation_gui_view": c("yes", "Chat per session, plans shown as artifacts"),
        "real_terminal": c("partial", "Terminal panel; the agent session itself is a chat"),
        "session_organization": c("yes", "Projects holding conversations; optional worktree"),
        "prompt_scratchpad": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "saved_prompt_library": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "builtin_editors_browser": c("partial", "Agent-driven browser; no code editor"),
        "appearance_control": c("partial", "Theme only; no font setting"),
        "usage_hud": c("yes", "Weekly and five-hour quota left, per model family"),
        "burn_rate_forecast": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "limit_governor": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "vault_task_source": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "issue_tracker_pipeline": c("partial", "Through GitHub's MCP server; no built-in issue-to-PR flow"),
        "worktree_management": c("yes", "Optional new git worktree per conversation"),
        "planner_orchestrator": c("yes", "Splits work into subagents; team mode in preview"),
        "agent_to_agent_messaging": c("experimental", "Preview team mode, through shared artifacts"),
        "knowledge_base": c("partial", "Rules, skills and documents; no searchable notes"),
        "native_mobile_app": c("no", "None; a web page you can add to the home screen"),
        "phone_no_new_app": c("yes", "Remote Control page in any phone browser"),
        "remote_ssh": c("partial", "Command-line version over SSH; not the desktop app"),
        "voice_input": c("yes", "Built-in dictation that strips filler words"),
        "os": c("info", "Windows, macOS, Linux; phone or browser via web page"),
        "app_shell": c("info", "Electron"),
        "languages": c("n/a", "Closed source"),
        "background_process": c("info", "Optional: remote-access service and helper processes"),
        "download_size": c("info", "164 MB Windows installer"),
        "ram_vs_claude_desktop": c("info", "Medium (estimate: Electron app)"),
        "runs_in_terminal": c("partial", "Separate command-line version; the app is its own window"),
        "license_cost": c("info", "Proprietary; free tier + paid plans"),
        "extensibility": c("yes", "Plugin marketplace, hooks, Python SDK in preview"),
        "teams_multiuser": c("partial", "Company sign-in and admin; no shared workspaces"),
        "stability_maturity": c("info", "Version 2.18; 2.0 launched May 2026; parts in preview"),
    },
}

# ---- Pane (greenfield-inc/Pane, "RunPane by Dcouple") ----
# Findings + sources: project_pantheon/archive/research_raw/2026-09-29-new-agent-managers/pane.md
pane = {
    "name": "Pane", "url": "https://github.com/greenfield-inc/Pane", "category": "agent manager",
    "where_agents_run": "your machine + a self-hosted remote host (VM, server, WSL, Mac mini) over Tailscale or SSH; phone or browser through its web app",
    "license": "AGPL-3.0, free", "checked_on": "2026-09-29 (repo/docs pass)",
    "source_note": "Checked against its README, docs/ folder, source code, latest release (v2.4.138) and runpane.com. Not installed or run here.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Any terminal agent side by side"),
        "harness_count": c("info", "Any CLI agent; 3 with built-in status reading"),
        "needs_you_signal": c("yes", "Status dots per pane read from the screen; phone push"),
        "approve_deny_prompt": c("partial", "Allow/deny dialog for Claude Code only, when enabled"),
        "cross_provider_delegation": c("yes", "Pane Chat hands work to agent panes, listed together"),
        "always_on_assistant": c("yes", "Pane Chat: standing orchestrator chat, reachable by phone"),
        "conversation_gui_view": c("no", "Terminals only, by design"),
        "real_terminal": c("yes", "Real terminal per agent, 50,000 lines of scrollback"),
        "session_organization": c("yes", "Projects, then panes (one worktree each), then tabs"),
        "prompt_scratchpad": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "saved_prompt_library": c("partial", "Text snippets on a shortcut; no attached context"),
        "builtin_editors_browser": c("yes", "Browser tab, code editor, file explorer, diff viewer"),
        "appearance_control": c("yes", "Light and dark palettes plus terminal font and size"),
        "usage_hud": c("partial", "Tokens and cost per pane; plan limits for Codex only"),
        "burn_rate_forecast": c("no", "Current use and reset only; no forecast"),
        "limit_governor": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "vault_task_source": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "issue_tracker_pipeline": c("partial", "Watches pull requests; issue trackers left to agents"),
        "worktree_management": c("yes", "Worktree per pane, cleanup, merge from the keyboard"),
        "planner_orchestrator": c("yes", "Pane Chat splits a goal into tickets and starts agents"),
        "agent_to_agent_messaging": c("yes", "Agents start and message other panes via its MCP server"),
        "knowledge_base": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "native_mobile_app": c("experimental", "iOS and Android test builds; not in the stores yet"),
        "phone_no_new_app": c("yes", "Browser web app; needs Tailscale or an SSH tunnel"),
        "remote_ssh": c("yes", "Agents, files and git on another machine"),
        "voice_input": c("partial", "Dictation in phone and browser; not desktop"),
        "os": c("info", "Windows, macOS, Linux; phone through the browser"),
        "app_shell": c("info", "Electron 41"),
        "languages": c("info", "TypeScript ~84%, Python ~7%"),
        "background_process": c("info", "Yes: a separate terminal-host process"),
        "download_size": c("info", "115 MB Windows installer"),
        "ram_vs_claude_desktop": c("info", "Medium (estimate: Electron app plus terminal host)"),
        "runs_in_terminal": c("no", "No; own desktop app with its own terminals"),
        "license_cost": c("info", "AGPL-3.0, free"),
        "extensibility": c("partial", "Scriptable command-line tool and MCP server; no plugins"),
        "teams_multiuser": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "stability_maturity": c("info", "v2.4.138, started February 2026, frequent releases"),
    },
}

claudedesktop = {
    "name": "Claude Desktop", "url": "https://claude.com/download", "category": "agent manager",
    "where_agents_run": "your machine (local, SSH, or WSL sessions) + Anthropic-managed cloud sessions; your phone reaches it through Dispatch and the Claude mobile app",
    "license": "Subscription: Pro $17-20/mo, Max $100-200/mo, Team $20-100/seat/mo (5-seat minimum), Enterprise $20/seat/mo plus API-rate usage",
    "checked_on": "2026-09-29 (docs pass)",
    "source_note": "Checked against code.claude.com/docs/en/desktop (the Code tab reference), support.claude.com (Cowork, install, voice), and claude.com/pricing. Not installed or run here.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("partial", "Claude Code; Codex needs unofficial add-ons"),
        "harness_count": c("info", "1 built in (Claude Code)"),
        "needs_you_signal": c("yes", "Desktop notification; phone push via Dispatch"),
        "approve_deny_prompt": c("yes", "Prompts in the session, pushed to your phone"),
        "cross_provider_delegation": c("partial", "Dispatch hands off in one sidebar; only Claude"),
        "always_on_assistant": c("yes", "Dispatch, a standing chat you can message any time"),
        "conversation_gui_view": c("yes", "Transcript views with tool calls summarized"),
        "real_terminal": c("yes", "Terminal pane in the session folder; local only"),
        "session_organization": c("yes", "Filterable sidebar list grouped by project"),
        "prompt_scratchpad": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "saved_prompt_library": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "builtin_editors_browser": c("yes", "File editor pane and a tabbed browser pane"),
        "appearance_control": c("partial", "Light or dark theme only; no font setting"),
        "usage_hud": c("yes", "Usage ring: session context and plan usage"),
        "burn_rate_forecast": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "limit_governor": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "vault_task_source": c("no", "None"),
        "issue_tracker_pipeline": c("partial", "GitHub and Linear connectors; no issue-to-PR flow"),
        "worktree_management": c("yes", "Optional git worktree per session"),
        "planner_orchestrator": c("partial", "Multi-step work in one session; no planner"),
        "agent_to_agent_messaging": c("yes", "Sessions can list, check on and message each other"),
        "knowledge_base": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "native_mobile_app": c("yes", "Claude iOS and Android app"),
        "phone_no_new_app": c("no", "Requires the Claude mobile app"),
        "remote_ssh": c("yes", "Runs Claude Code on a remote Linux or Mac machine"),
        "voice_input": c("partial", "Dictation on macOS only; not on Windows"),
        "os": c("info", "macOS, Windows; Linux beta; iOS/Android app"),
        "app_shell": c("info", "Electron"),
        "languages": c("n/a", "Closed source"),
        "background_process": c("info", "Yes: Cowork starts a virtual machine"),
        "download_size": c("info", "Not published; Windows installer downloads the app"),
        "ram_vs_claude_desktop": c("info", "The reference: about 7.5 GB measured"),
        "runs_in_terminal": c("no", "Own app window with a terminal pane inside"),
        "license_cost": c("info", "Proprietary; paid plans from $17 a month"),
        "extensibility": c("yes", "Connectors, plugins, MCP servers and hooks"),
        "teams_multiuser": c("yes", "Team and Enterprise plans with admin controls"),
        "stability_maturity": c("info", "Stable on macOS and Windows; Linux in beta"),
    },
}

# Research entry for agent-manager (https://github.com/YoanWai/agent-manager), checked 2026-09-29.
# Shape matches the orca/ao entries in portfolio_repos/agent-deck-comparison/tools/build_data.py.
# Findings and sources: project_pantheon/archive/research_raw/2026-09-29-new-agent-managers/agent-manager.md
agentmanager = {
    "name": "agent-manager", "url": "https://github.com/YoanWai/agent-manager", "category": "agent manager",
    "where_agents_run": "your machine, each agent in its own tmux session (Windows only inside WSL2)",
    "license": "Apache-2.0, free", "checked_on": "2026-09-29 (repo pass)",
    "source_note": "Repo-verified: README, docs/, release assets, go.mod and source read; not installed.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Nine CLI agents in one list, each in tmux"),
        "harness_count": c("info", "9 named, plus plain shell tabs"),
        "needs_you_signal": c("yes", "Waiting mark, attention filter, desktop notification"),
        "approve_deny_prompt": c("partial", "Answer from the list by typing; no allow or deny control"),
        "cross_provider_delegation": c("yes", "Agents start other agents; all in the same list"),
        "always_on_assistant": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "conversation_gui_view": c("partial", "Last message and reply per row; no full chat view"),
        "real_terminal": c("yes", "Attach to its real tmux session full screen"),
        "session_organization": c("yes", "Nested groups in a folding tree"),
        "prompt_scratchpad": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "saved_prompt_library": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "builtin_editors_browser": c("partial", "Diff review with line comments; no editor or browser"),
        "appearance_control": c("partial", "17 color themes; no font setting"),
        "usage_hud": c("no", "None; \"cost tracking\" listed as not here yet"),
        "burn_rate_forecast": c("no", "None"),
        "limit_governor": c("no", "Rate limits only mark the session errored"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "vault_task_source": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "issue_tracker_pipeline": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "worktree_management": c("yes", "Optional worktree and branch per session"),
        "planner_orchestrator": c("partial", "Agents share a task list; no built-in planner"),
        "agent_to_agent_messaging": c("yes", "Queued messages through its built-in MCP server"),
        "knowledge_base": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "native_mobile_app": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "phone_no_new_app": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "remote_ssh": c("partial", "Runs on a machine you SSH into; can't manage another"),
        "voice_input": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "os": c("info", "macOS, Linux; Windows only inside WSL2"),
        "app_shell": c("info", "Terminal UI in Go, over tmux"),
        "languages": c("info", "Go ~99.8%"),
        "background_process": c("info", "Its own tmux server; no separate daemon"),
        "download_size": c("info", "8 MB archive; no Windows file"),
        "ram_vs_claude_desktop": c("info", "Tiny (estimate: a Go terminal program plus tmux)"),
        "runs_in_terminal": c("yes", "Runs inside your own terminal"),
        "license_cost": c("info", "Apache-2.0, free"),
        "extensibility": c("partial", "MCP server and CLI commands; no plugin system"),
        "teams_multiuser": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "stability_maturity": c("info", "Since July 2026, 540 stars, releases most weeks"),
    },
}

# ---- VibeTree ----
vibetree = {
    "name": "VibeTree", "url": "https://github.com/sahithvibudhi/vibe-tree", "category": "agent manager",
    "where_agents_run": "your machine, or a server you run yourself (home server or VM) reached from any browser or phone",
    "license": "MIT, free", "checked_on": "2026-09-29 (repo pass)",
    "source_note": "Repo-verified: README, docs site, v0.2.0 release notes and source read at commit f889077 (2026-07-25); not installed.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Any CLI agent, one terminal per worktree"),
        "harness_count": c("info", "Any terminal program; 5 named"),
        "needs_you_signal": c("yes", "Sidebar status, a ding and desktop notifications"),
        "approve_deny_prompt": c("partial", "Flags waiting prompts; no buttons, you type the answer"),
        "cross_provider_delegation": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "always_on_assistant": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "conversation_gui_view": c("no", "Terminals only; no chat view"),
        "real_terminal": c("yes", "Persistent terminals with splits and search"),
        "session_organization": c("yes", "Project tabs, each with a list of worktrees"),
        "prompt_scratchpad": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "saved_prompt_library": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "builtin_editors_browser": c("partial", "Browser preview and diff viewer; no code editor"),
        "appearance_control": c("partial", "Terminal font and size; no theme picker"),
        "usage_hud": c("no", "None"),
        "burn_rate_forecast": c("no", "None"),
        "limit_governor": c("no", "None"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "vault_task_source": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "issue_tracker_pipeline": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "worktree_management": c("yes", "Core: one worktree and branch per task"),
        "planner_orchestrator": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "agent_to_agent_messaging": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "knowledge_base": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "native_mobile_app": c("no", "No store app; installable web app instead"),
        "phone_no_new_app": c("yes", "Phone browser, paired by QR code"),
        "remote_ssh": c("partial", "Standalone server for another machine; no SSH mode"),
        "voice_input": c("no", "None"),
        "os": c("info", "Windows, macOS, Linux; any browser via its server"),
        "app_shell": c("info", "Electron 38"),
        "languages": c("info", "TypeScript ~89%, HTML ~8%"),
        "background_process": c("info", "Desktop: no; browser and phone need its Node server"),
        "download_size": c("info", "98 MB Windows installer"),
        "ram_vs_claude_desktop": c("info", "Small (estimate: one Electron app)"),
        "runs_in_terminal": c("partial", "Its CLI lists and starts agents; terminals live in the app"),
        "license_cost": c("info", "MIT, free, no telemetry"),
        "extensibility": c("partial", "Hook scripts and a CLI; no plugins or SDK"),
        "teams_multiuser": c("partial", "Shareable project settings; no user accounts"),
        "stability_maturity": c("info", "Early: v0.2.0, two releases, ~270 stars"),
    },
}

# ---- Researched 2026-09-29 for the "Most used" default view; sources in project_pantheon/archive/research_raw/2026-09-29-new-agent-managers/ ----
vibekanban = {
    "name": "vibe-kanban", "url": "https://github.com/BloopAI/vibe-kanban", "category": "agent manager",
    "where_agents_run": "your machine (desktop app or a local web server opened in your browser); a self-hosted server you reach through a tunnel; phone or another computer through the browser after pairing",
    "license": "Apache-2.0, free", "checked_on": "2026-09-29 (repo/docs pass)",
    "source_note": "Checked against its README, docs/ folder, source code, releases (last stable v0.1.44, 2026-04-24; npx-only v0.1.45 prerelease, 2026-09-19) and the shutdown announcement at vibekanban.com/blog/shutdown. The company announced a sunset on 2026-04-10; the kanban board and hosted issues were retired in v0.1.44 and the project is now community maintained. Not installed or run here.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Different agent per workspace, run side by side"),
        "harness_count": c("info", "10, including Claude Code, Codex, Gemini CLI, Copilot"),
        "needs_you_signal": c("yes", "Sounds and system notifications; approval cards in chat"),
        "approve_deny_prompt": c("yes", "Approve or deny cards in its chat, for most agents"),
        "cross_provider_delegation": c("partial", "Several agents share one workspace; no hand-off view"),
        "always_on_assistant": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "conversation_gui_view": c("yes", "Each session is a formatted chat with tool calls"),
        "real_terminal": c("partial", "Terminal for your own commands; not the agent's"),
        "session_organization": c("yes", "Workspaces holding chat sessions; kanban board retired"),
        "prompt_scratchpad": c("partial", "One unsent draft per session; no set of saved drafts"),
        "saved_prompt_library": c("partial", "Reusable text snippets via @; no attached context"),
        "builtin_editors_browser": c("yes", "Preview browser with devtools, diff viewer"),
        "appearance_control": c("partial", "Light and dark themes; no font setting"),
        "usage_hud": c("partial", "Context gauge per session; no Claude plan limits"),
        "burn_rate_forecast": c("no", "No burn rate or time to the limit"),
        "limit_governor": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "vault_task_source": c("no", "No notes-vault reading"),
        "issue_tracker_pipeline": c("partial", "Creates and merges pull requests; no issue intake"),
        "worktree_management": c("yes", "Worktree and branch per workspace, with merge and cleanup"),
        "planner_orchestrator": c("partial", "Outside agent can split a plan via MCP; no built-in planner"),
        "agent_to_agent_messaging": c("yes", "Agents prompt and read other sessions via its MCP server"),
        "knowledge_base": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "native_mobile_app": c("no", "No phone app; browser only"),
        "phone_no_new_app": c("unknown", "Phone browser pairing via its cloud; untested since shutdown"),
        "remote_ssh": c("partial", "Can run on a remote server; no remote agents from local app"),
        "voice_input": c("no", "No dictation"),
        "os": c("info", "Windows, macOS, Linux; any browser"),
        "app_shell": c("info", "Tauri 2, or a local web server via npx"),
        "languages": c("info", "Rust ~50%, TypeScript ~46%"),
        "background_process": c("info", "None; its server runs inside the app"),
        "download_size": c("info", "39 MB Windows installer"),
        "ram_vs_claude_desktop": c("info", "Small (estimate: Tauri app, server in same process)"),
        "runs_in_terminal": c("no", "No; desktop app or browser page"),
        "license_cost": c("info", "Apache-2.0, free; paid hosted plans ended"),
        "extensibility": c("partial", "MCP server and agent settings; no plugins or SDK"),
        "teams_multiuser": c("partial", "Hosted teams removed; self-hosted teams unconfirmed"),
        "stability_maturity": c("info", "Shutdown announced April 2026; community maintained"),
    },
}

t3code = {
    "name": "T3 Code", "url": "https://github.com/pingdotgg/t3code", "category": "agent manager",
    "where_agents_run": "your machine + another machine you pair or reach over SSH (Linux or Apple Silicon Mac); phone, browser or another desktop app control it through T3 Connect, Tailscale or a local network",
    "license": "MIT, free", "checked_on": "2026-09-29 (repo/docs pass)",
    "source_note": "Checked against its README, docs/ folder, source code at commit 4222485, latest stable release (v0.0.43) and t3.codes. Not installed or run here.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "6 agents side by side in one sidebar, your own logins"),
        "harness_count": c("info", "6: Claude Code, Codex, Cursor, Grok, OpenCode, Antigravity"),
        "needs_you_signal": c("yes", "Colored thread status, desktop alerts, phone push"),
        "approve_deny_prompt": c("yes", "Approve or reject in chat on desktop, web or phone"),
        "cross_provider_delegation": c("partial", "All agents in one sidebar; no agent-to-agent hand-off"),
        "always_on_assistant": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "conversation_gui_view": c("yes", "Chat threads with expandable tool calls"),
        "real_terminal": c("partial", "Shell drawer per thread; not the agent's own terminal"),
        "session_organization": c("yes", "Projects, then threads, optional worktree per thread"),
        "prompt_scratchpad": c("yes", "Prompt stash saves a prompt without sending"),
        "saved_prompt_library": c("partial", "Prompt stash with context; no lasting named library"),
        "builtin_editors_browser": c("yes", "Editor, diff viewer, preview browser, phone emulators"),
        "appearance_control": c("yes", "Custom themes plus font family and size everywhere"),
        "usage_hud": c("yes", "Tokens, cost and plan limits with resets per provider"),
        "burn_rate_forecast": c("partial", "Pace mark per limit; no predicted time to the limit"),
        "limit_governor": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "account_hotswap": c("yes", "Several accounts per provider, picked per thread"),
        "vault_task_source": c("no", "No notes-vault reading"),
        "issue_tracker_pipeline": c("partial", "Full pull request flow on 6 hosts; no issue intake"),
        "worktree_management": c("yes", "New worktree per thread, one per model"),
        "planner_orchestrator": c("partial", "Plan mode for one agent; no splitting across agents"),
        "agent_to_agent_messaging": c("no", "No way for one thread to message another"),
        "knowledge_base": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "native_mobile_app": c("yes", "iOS and Android apps in the stores"),
        "phone_no_new_app": c("yes", "Hosted web app in the phone browser; needs HTTPS access"),
        "remote_ssh": c("yes", "Installs its server on a remote host over SSH"),
        "voice_input": c("partial", "Dictation in the iPhone app only"),
        "os": c("info", "Windows, macOS, Linux; iOS, Android; any browser"),
        "app_shell": c("info", "Electron 44, also served as a web app"),
        "languages": c("info", "TypeScript ~96%, MDX ~2%"),
        "background_process": c("info", "Yes: bundled server that runs agents, terminals, git"),
        "download_size": c("info", "209 MB Windows installer"),
        "ram_vs_claude_desktop": c("info", "Medium (estimate: Electron app plus a Node server)"),
        "runs_in_terminal": c("no", "No; own desktop, web and phone apps"),
        "license_cost": c("info", "MIT, free"),
        "extensibility": c("no", "No plugins or SDK; custom themes only"),
        "teams_multiuser": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "stability_maturity": c("info", "v0.0.43, started February 2026; README says very early"),
    },
}

# Research entry for Wave Terminal (https://www.waveterm.dev), checked 2026-09-29.
# Shape matches the pane entry in portfolio_repos/agent-deck-comparison/tools/build_data.py.
# Findings and sources: project_pantheon/archive/research_raw/2026-09-29-new-agent-managers/wave-terminal.md
wave = {
    "name": "Wave Terminal", "url": "https://www.waveterm.dev", "category": "agent manager",
    "where_agents_run": "your machine, plus remote machines over SSH (sessions can keep running there after you disconnect) and WSL",
    "license": "Apache-2.0, free", "checked_on": "2026-09-29 (repo/docs pass)",
    "source_note": "Checked against its README, ROADMAP.md, docs/ folder (docs.waveterm.dev source), source code at commit c58bf7f (2026-09-25), latest release (v0.14.5) and waveterm.dev. Not installed or run here.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("yes", "Any CLI agent in tiled terminal blocks"),
        "harness_count": c("info", "Any CLI agent; only Claude Code has a documented setup"),
        "needs_you_signal": c("yes", "Tab badges via Claude Code hooks, optional beep"),
        "approve_deny_prompt": c("no", "Badge points you there; you answer in its terminal"),
        "cross_provider_delegation": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "always_on_assistant": c("partial", "Wave AI side panel; can't run commands or direct agents"),
        "conversation_gui_view": c("no", "Terminals only; chat is just its own AI panel"),
        "real_terminal": c("yes", "Full terminal in every block"),
        "session_organization": c("yes", "Workspaces, then tabs, then tiled terminal blocks"),
        "prompt_scratchpad": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "saved_prompt_library": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "builtin_editors_browser": c("yes", "Code editor, web browser and file previews"),
        "appearance_control": c("yes", "Themes, backgrounds, terminal font and size"),
        "usage_hud": c("no", "None; only its own AI panel's allowance"),
        "burn_rate_forecast": c("no", "None"),
        "limit_governor": c("no", "None"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "vault_task_source": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "issue_tracker_pipeline": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "worktree_management": c("no", "None"),
        "planner_orchestrator": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "agent_to_agent_messaging": c("partial", "Can read another block's output; can't send it input"),
        "knowledge_base": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "native_mobile_app": c("no", "Desktop only"),
        "phone_no_new_app": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "remote_ssh": c("yes", "One-click SSH and WSL; sessions survive disconnects"),
        "voice_input": c("no", "None"),
        "os": c("info", "Windows, macOS, Linux; no phone or browser access"),
        "app_shell": c("info", "Electron 41 with a Go backend"),
        "languages": c("info", "Go ~49%, TypeScript ~43%"),
        "background_process": c("info", "Yes: its own Go server process"),
        "download_size": c("info", "156 MB Windows installer"),
        "ram_vs_claude_desktop": c("info", "Medium (estimate: Electron plus a Go server)"),
        "runs_in_terminal": c("no", "Is its own terminal app"),
        "license_cost": c("info", "Apache-2.0, free; AI panel has free beta credits"),
        "extensibility": c("partial", "Custom widgets and a scripting CLI; no plugins or SDK"),
        "teams_multiuser": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "stability_maturity": c("info", "Since 2022, ~22,400 stars; no release since April 2026"),
    },
}

# Research entry for ChatGPT Desktop (OpenAI; home of the former Codex app), checked 2026-09-29.
# Shape matches the pane / claudedesktop entries in portfolio_repos/agent-deck-comparison/tools/build_data.py.
# Findings and sources: project_pantheon/archive/research_raw/2026-09-29-new-agent-managers/codex-app.md
# Note: on 2026-07-09 the standalone Codex app merged into the ChatGPT desktop app; Codex keeps its own view there.
codexapp = {
    "name": "ChatGPT Desktop", "url": "https://learn.chatgpt.com/docs/app", "category": "agent manager",
    "where_agents_run": "your machine (local checkout or a git worktree per chat) + SSH hosts + OpenAI-hosted Codex cloud chats; your phone reaches the desktop through Remote in the ChatGPT mobile app",
    "license": "Closed source; included in every ChatGPT plan: Free $0, Go $8/mo, Plus $20/mo, Pro $100-500/mo, Business $20/user/mo, Enterprise and Edu by contract",
    "checked_on": "2026-09-29 (docs pass)",
    "source_note": "Checked against learn.chatgpt.com (the Codex and ChatGPT desktop app docs that developers.openai.com/codex/app now redirects to), its What's new page, the pricing page, the official download links, and openai/codex GitHub issues for the app shell. Since 2026-07-09 the Codex app ships inside the ChatGPT desktop app. Not installed or run here.",
    "is_authors_own": False,
    "features": {
        "multi_provider_supervision": c("no", "Only Codex"),
        "harness_count": c("info", "1 (Codex)"),
        "needs_you_signal": c("yes", "Notifications plus a waiting-on-you activity list"),
        "approve_deny_prompt": c("yes", "Approve in the chat or from the phone app"),
        "cross_provider_delegation": c("partial", "Subagent threads shown; only Codex agents"),
        "always_on_assistant": c("partial", "Always-on cloud agent; still rolling out"),
        "conversation_gui_view": c("yes", "Chat view with diffs and subagent threads inline"),
        "real_terminal": c("yes", "Terminal per chat, scoped to its project"),
        "session_organization": c("yes", "Projects holding chats; optional worktree per chat"),
        "prompt_scratchpad": c("partial", "Editable queue of follow-ups; no drafts area"),
        "saved_prompt_library": c("partial", "Skills and scheduled prompts; no saved-prompt list"),
        "builtin_editors_browser": c("yes", "Built-in browser, diff editing, pull request view"),
        "appearance_control": c("yes", "Themes, colors, separate interface and code fonts"),
        "usage_hud": c("partial", "Token counts; plan limits and resets only on the web"),
        "burn_rate_forecast": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "limit_governor": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "account_hotswap": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "vault_task_source": c("undocumented", "Not in its docs (checked 2026-09-29)"),
        "issue_tracker_pipeline": c("partial", "Linear issues and pull request reviews; runs in the cloud"),
        "worktree_management": c("yes", "Creates and cleans up a worktree per chat"),
        "planner_orchestrator": c("yes", "Splits a task across subagents when asked"),
        "agent_to_agent_messaging": c("partial", "Subagents report to their parent; not chat to chat"),
        "knowledge_base": c("partial", "Memories and project instructions; no notes store"),
        "native_mobile_app": c("yes", "ChatGPT iOS and Android app"),
        "phone_no_new_app": c("no", "Requires the ChatGPT mobile app"),
        "remote_ssh": c("yes", "Runs chats on hosts from your SSH config"),
        "voice_input": c("yes", "Dictation with cleanup, plus spoken conversation"),
        "os": c("info", "macOS, Windows, Linux (preview); iOS/Android app"),
        "app_shell": c("info", "Electron"),
        "languages": c("n/a", "Closed source; its Rust app server is open source"),
        "background_process": c("info", "Yes: a Codex app server process"),
        "download_size": c("info", "744 MB mac dmg, 475 MB Linux .deb"),
        "ram_vs_claude_desktop": c("info", "Medium (estimate: Electron app plus a server)"),
        "runs_in_terminal": c("no", "Own app window; Codex CLI is the terminal tool"),
        "license_cost": c("info", "Proprietary; free tier + paid ChatGPT plans"),
        "extensibility": c("yes", "Plugins, skills, MCP servers, hooks and an SDK"),
        "teams_multiuser": c("yes", "Business and Enterprise workspaces with admin"),
        "stability_maturity": c("info", "Launched Feb 2026; Linux in preview"),
    },
}

# ---- Listed 2026-09-29, not researched yet: every cell Unknown until a research pass ----
def placeholder(name, url, note):
    return {
        "name": name, "url": url, "category": "agent manager", "where_agents_run": "not verified",
        "license": "not verified", "checked_on": "not researched yet (listed 2026-09-29)",
        "source_note": note, "is_authors_own": False,
        "features": {k: c("unknown", "Not researched yet") for k, _, _, _ in FEATURES},
    }

agtx = placeholder("AGTX", "https://github.com/thereal4th/AGTX",
                   "Listed 2026-09-29, research pending. Its README describes an orchestrator agent that hands tasks from a terminal kanban board to coding agents running in parallel.")
nimbalyst = placeholder("Nimbalyst", "https://nimbalyst.com", "Listed 2026-09-29, research pending.")
parallelcode = placeholder("Parallel Code", "https://github.com/johannesjo/parallel-code", "Listed 2026-09-29, research pending.")

# Column order (owner decision 2026-09-29): the "Featured" set first, picked for how versatile they
# are; then every other researched tool A-Z; then tools not researched yet.
FEATURED = [orca, velaterm, herdr, paseo, ao, pane, pantheon]
PENDING = [agtx, nimbalyst, parallelcode]
_rest = [antigravity, claudedesktop, codexapp, superset, opencove, ccmanager, agentmanager, micracode,
         vibetree, jenny, vibekanban, conductor, kepler, teleclod, oyren, t3code, wave]
TOOLS = FEATURED + sorted(_rest, key=lambda t: t["name"].lower()) + PENDING

# GitHub stars, read from the GitHub API on 2026-09-29. None = closed source, no public repo.
STARS = {
    "Orca": 81580, "herdr": 41461, "vibe-kanban": 28221, "T3 Code": 23911, "Wave Terminal": 22388,
    "Paseo": 19013, "Superset": 14740, "Agent Orchestrator (AO)": 12530, "Nimbalyst": 1803,
    "OpenCove": 1600, "CCManager": 1256, "Parallel Code": 1026, "agent-manager": 540, "Pane": 497,
    "micracode": 289, "VibeTree": 267, "VelaTerm": 230, "Jenny": 47, "AGTX": 0, "Pantheon": 0,
}
for t in TOOLS:
    t["github_stars"] = STARS.get(t["name"])

# Operating systems: release assets / vendor pages as recorded in the source doc and the raw-evidence
# file (2026-09-28). Anything not on record stays "not verified".
OS = {
    "Orca": c("info", "Windows, macOS, Linux; phone companion (beta)"),
    "VelaTerm": c("info", "Windows, macOS, Linux; iOS/Android app; any browser"),
    "herdr": c("info", "macOS, Linux, Windows (beta)"),
    "Pantheon": c("info", "Windows only (MSYS2 + tmux); phone over SSH"),
    "Paseo": c("info", "Windows, macOS, Linux; iOS/Android; web"),
    "GitKraken Kepler": c("info", "Windows, macOS, Linux; mobile check-and-answer"),
    "Agent Orchestrator (AO)": c("info", "Windows, macOS, Linux; mobile companion"),
    "CCManager": c("info", "Linux, macOS"),
    "Superset": c("info", "macOS; Linux experimental"),
    "Conductor": c("info", "macOS only"),
    "Jenny": c("info", "Windows (macOS untested, no Linux)"),
    "Teleclod": c("info", "Windows, macOS, Linux, Android; browser"),
    "Oyren": c("info", "Any browser (hosted)"),
}
for t in TOOLS:
    if t["name"] in OS:
        t["features"]["os"] = OS[t["name"]]

out = {
    "snapshot_date": "2026-09-29",
    "snapshot_note": "Snapshot as of 2026-09-29. Cells come from each tool's own docs/posts at the dates shown; not re-verified beyond that pass.",
    "features": [{"key": k, "label": label, "description": desc, "group": group} for k, label, desc, group in FEATURES],
    "group_order": GROUP_ORDER,
    "tools": TOOLS,
}

here = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(here, "..", "data", "tools.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)

unknown_counts = {}
for t in TOOLS:
    n = sum(1 for v in t["features"].values() if v["mark"] == "unknown")
    unknown_counts[t["name"]] = n

print("Wrote", out_path)
print("Tools:", len(TOOLS))
for name, n in unknown_counts.items():
    print(f"  {name}: {n} unknown cells")
